version: '3.9'

services:
  application:
    container_name: application
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./application:/application
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
    restart: always
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - 5432:5432
