# Generated by Django 4.2.3 on 2023-08-02 23:19

import core.utils.select_current_values_db
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('name', models.CharField(max_length=200)),
                ('identity', models.CharField(max_length=17, unique=True)),
                ('_type', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.organization')),
            ],
            options={
                'verbose_name': 'Adress',
                'verbose_name_plural': 'Adresses',
                'db_table': 'adresses',
            },
        ),
    ]
