# Generated by Django 4.2.3 on 2023-08-02 21:09

import core.utils.select_current_values_db
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_organization_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.organization')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
            },
        ),
    ]
