# Generated by Django 4.2.3 on 2023-07-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ornanization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ornanization',
        ),
    ]
