# Generated by Django 4.2.3 on 2023-08-12 15:39

import core.utils.select_current_values_db
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'EntityCategory',
                'verbose_name_plural': 'EntityCategories',
                'db_table': 'entity_categories',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('name', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=22, unique=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.entitycategory')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity')),
            ],
            options={
                'verbose_name': 'Adress',
                'verbose_name_plural': 'Adresses',
                'db_table': 'adresses',
            },
        ),
    ]
