# Generated by Django 4.2.3 on 2023-08-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_address_entity_alter_contact_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='app.entity'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='app.entity'),
        ),
    ]
