# Generated by Django 4.2.3 on 2023-08-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_address_entity_alter_contact_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.entitycategory'),
        ),
    ]
