# Generated by Django 4.2.3 on 2023-08-21 21:27

import core.utils.select_current_values_db
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productcategory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_destination', to='app.address')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database)),
                ('updated_at', models.DateTimeField(default=core.utils.select_current_values_db.get_current_date_time_database, null=True)),
                ('username_create', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('username_update', models.CharField(default=core.utils.select_current_values_db.get_current_user_database, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
