# Generated by Django 4.2.3 on 2023-09-02 11:52

import core.utils.enums.StatusOrder
import core.utils.enums.StatusPayment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_itemorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'OPEN'), (2, 'IN_PROGRESS'), (3, 'CLOSED')], default=core.utils.enums.StatusOrder.StatusOrder['OPEN']),
        ),
        migrations.AddField(
            model_name='order',
            name='status_payment',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'COMPLETE'), (3, 'CANCELED')], default=core.utils.enums.StatusPayment.StatusPayment['PENDING']),
        ),
        migrations.AddField(
            model_name='order',
            name='total_value_order',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
    ]
