# Generated by Django 4.2.3 on 2023-09-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_status_order_status_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_value_order',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=13),
        ),
    ]
