# Generated by Django 4.2.3 on 2023-09-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_total_value_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name': 'Item_Order', 'verbose_name_plural': 'Itens_Orders'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelTable(
            name='itemorder',
            table='itens_orders',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
