# Generated by Django 4.2.3 on 2023-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_itemorder_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=13),
        ),
    ]
