# Generated by Django 4.2.3 on 2024-04-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_itemorder_total_value_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
